In [1]:
X = [[0,1],[1.1,0.1],[1,0], [1.1, 0.05], [-0.1,0.5]]

In [2]:
X

[[0, 1], [1.1, 0.1], [1, 0], [1.1, 0.05], [-0.1, 0.5]]

In [3]:
import numpy as np

In [5]:
X = np.array(X)

In [9]:
X

array([[ 0.  ,  1.  ],
       [ 1.1 ,  0.1 ],
       [ 1.  ,  0.  ],
       [ 1.1 ,  0.05],
       [-0.1 ,  0.5 ]])

In [10]:
y = [0,1,1,1,0]

In [12]:
y = np.array(y)

In [14]:
y.shape

(5,)

In [16]:
y = y.reshape(-1,1)

In [21]:
y.ravel()

array([0, 1, 1, 1, 0])

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
knn = KNeighborsClassifier(n_neighbors=3)

In [20]:
knn.fit(X,y)

/home/nobleprog/Desktop/ml-bespoke/env/lib/python3.10/site-packages/sklearn/neighbors/_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [22]:
knn.predict([[1.2,0.3]])

array([1])

In [23]:
knn.predict_proba([[1.2,0.3]])

array([[0., 1.]])

In [24]:
knn.predict([[0.5,0.5]])

array([0])

In [25]:
knn.predict_proba([[0.5,0.5]])

array([[0.66666667, 0.33333333]])

In [26]:
X[0]

array([0., 1.])

In [29]:
np.sqrt(np.sum((X[0]-[0.5,0.5])**2))

0.7071067811865476

In [30]:
np.sqrt(np.sum((X[1]-[0.5,0.5])**2))

0.7211102550927979

In [31]:
np.sqrt(np.sum((X[2]-[0.5,0.5])**2))

0.7071067811865476

In [32]:
np.sqrt(np.sum((X[3]-[0.5,0.5])**2))

0.7500000000000001

In [33]:
np.sqrt(np.sum((X[4]-[0.5,0.5])**2))

0.6

In [34]:
y[0],y[2],y[4]

(array([0]), array([1]), array([0]))